# How to use the Tax Calculator

This guide teaches you how to use the Open Source Policy Center's Tax Calculator. To follow along you will need the following: 

1. A copy of the taxcalc package installed on your local machine.
2. A copy of the 2008 IRS public use file.

### Import taxcalc package and other useful packages

In [1]:
import sys
sys.path.append("../../")
import taxcalc
from taxcalc import *
import pandas as pd
from pandas import DataFrame

### Create a 'Plan X' calculator using the default parameters

In [3]:
# Default Plans
#Create a Public Use File object
tax_dta = pd.read_csv("../../puf.csv")
# Create a default Parameters object
params1 = Policy(start_year=2013)
records1 = Records(tax_dta)
# Create a Calculator
calcX = Calculator(records=records1, policy=params1)
calcX.increment_year()
calcX.increment_year()

You loaded data for 2009.
Your data have been extrapolated to 2013.

#### Calculate taxes for your Plan X

In [4]:
calcX.calc_all()

#### Now create an output table with intermediate and final tax variables broken down by income decile

In [5]:
tX = create_distribution_table(calcX, groupby="weighted_deciles", result_type="weighted_sum")

In [11]:
DIST_LABELS = ['Returns', 'AGI', 'Standard Deduction Filers',
                'Standard Deduction', 'Itemizers',
                'Itemized Deduction', 'Personal Exemption',
                'Taxable Income', 'Regular Tax', 'AMTI', 'AMT Filers', 'AMT',
                'Tax before Credits', 'Non-refundable Credits',
                'Tax before Refundable Credits', 'Refundable Credits',
                'Individual Income Tax Liabilities', 'Payroll Tax Liablities',
                'Combined Payroll and Individual Income Tax Liabilities']

In [12]:
tX.columns = DIST_LABELS

This table matches taxbrain/893

In [13]:
tX

,Returns,AGI,Standard Deduction Filers,Standard Deduction,Itemizers,Itemized Deduction,Personal Exemption,Taxable Income,Regular Tax,AMTI,AMT Filers,AMT,Tax before Credits,Non-refundable Credits,Tax before Refundable Credits,Refundable Credits,Individual Income Tax Liabilities,Payroll Tax Liablities,Combined Payroll and Individual Income Tax Liabilities
0,"15,138,474","-102,458,011,349","12,797,116","87,518,769,407","19,629","75,765,069","56,716,721,967","722,383,555","72,238,356","-31,003,573,978","11,100","2,781,314,704","2,815,855,909","4,795,903","4,588,603,432","5,687,290,291","-1,098,686,859","8,254,002,854","7,155,315,995"
1,"15,137,366","134,663,112,759","14,466,867","112,737,477,612","172,634","1,889,997,739","85,958,817,242","9,334,755,513","934,304,942","1,820,128,339",440,"40,450,591","938,542,177","47,458,805","5,132,651,132","22,630,700,059","-17,498,048,927","19,096,854,697","1,598,805,770"
2,"15,139,393","223,984,396,286","14,313,087","119,549,407,663","479,601","6,162,873,622","109,678,347,641","43,569,150,046","4,415,526,928","3,019,799,581",668,"129,312,802","4,458,997,384","712,886,713","8,511,901,882","32,446,023,266","-23,934,121,384","31,776,179,495","7,842,058,111"
3,"15,138,598","316,704,710,238","13,877,262","120,475,684,036","1,127,450","16,515,771,798","110,988,947,271","100,279,447,150","11,328,855,287","5,464,360,731","1,862","278,487,738","11,445,191,122","2,460,891,785","12,503,210,362","22,958,151,662","-10,454,941,300","42,458,340,155","32,003,398,855"
4,"15,139,054","429,790,012,326","12,790,939","116,954,488,832","2,286,070","35,738,811,513","110,797,117,681","188,925,033,024","22,726,921,146","7,899,544,996","4,105","259,251,417","22,567,457,019","4,385,019,730","21,442,329,952","14,437,566,416","7,004,763,536","53,520,282,879","60,525,046,415"
5,"15,138,851","593,989,155,264","11,538,289","113,381,628,548","3,588,043","61,605,110,040","113,842,025,527","319,023,439,972","40,518,652,894","15,864,544,908","4,670","304,932,562","39,991,244,587","6,297,318,577","36,968,722,656","6,861,418,309","30,107,304,347","70,732,424,312","100,839,728,660"
6,"15,138,689","814,574,042,212","9,696,476","104,336,825,487","5,439,078","101,489,653,278","122,603,368,976","491,519,279,342","67,887,540,987","27,440,365,931","9,824","228,927,791","66,830,560,926","8,481,927,171","62,389,514,538","3,724,688,421","58,664,826,117","93,381,711,944","152,046,538,061"
7,"15,138,398","1,135,796,473,103","7,764,888","90,994,317,541","7,369,830","150,434,067,660","134,949,325,669","760,674,593,575","113,292,149,254","58,062,269,014","53,494","534,202,166","111,276,333,045","10,268,269,534","106,029,961,280","3,604,692,023","102,425,269,258","128,198,420,268","230,623,689,526"
8,"15,138,461","1,652,045,123,956","4,944,170","62,625,963,964","10,194,069","242,144,818,593","157,605,869,080","1,190,982,713,656","191,716,383,780","117,147,899,869","178,185","684,381,412","188,391,544,838","12,465,151,600","182,854,484,482","3,767,898,614","179,086,585,869","202,541,872,427","381,628,458,295"
9,"15,139,730","4,927,328,963,833","2,055,084","25,935,470,685","13,083,561","600,458,416,144","149,315,042,649","4,154,676,902,931","1,157,891,405,357","2,758,015,614,054","4,201,378","29,298,765,603","1,064,631,377,890","26,448,410,156","1,087,820,867,409","1,749,327,286","1,086,071,540,123","347,413,523,815","1,433,485,063,938"
sums,"151,387,013","10,126,417,978,626","104,244,179","954,510,033,775","43,759,967","1,216,515,285,457","1,152,455,583,703","7,259,707,698,766","1,610,783,978,932","2,963,730,953,445","4,465,726","34,540,026,787","1,513,347,104,897","71,572,129,973","1,528,242,247,126","117,867,756,346","1,410,374,490,780","997,373,612,846","2,407,748,103,626"

#### Then create a 'Plan Y' calculator using a parameter file that contains plan Y tax law.

##### In this case, we are using an example param file in which the state and local deduction haircut has been set to 100%, effectively repealing the deduction for state and local taxes.

In [27]:
# User specified Plans
myvars = {}
myvars['_SS_Earnings_c'] = [1e+21]
myvars['_ID_BenefitSurtax_Switch'] = [[True, True, True, True, True, True, True]]
user_mods = {2015: myvars}

params2 = Policy(start_year=2013)
params2.implement_reform(user_mods)
#Create a Public Use File object
tax_dta = pd.read_csv("../../puf.csv")
# Create a default Parameters object
records2 = Records(tax_dta)

# Create a Calculator
calcY = Calculator(policy=params2, records=records2)
calcY.increment_year()
calcY.increment_year()

You loaded data for 2009.
Your data have been extrapolated to 2013.

In [28]:
calcY.calc_all()

#### Create an output table with intermediate and final tax variables broken down by income decile

In [29]:
tY = create_distribution_table(calcY, groupby="weighted_deciles", result_type="weighted_sum")

In [30]:
tY.columns = DIST_LABELS

This distributional table matches taxbrain/892

In [31]:
tY

,Returns,AGI,Standard Deduction Filers,Standard Deduction,Itemizers,Itemized Deduction,Personal Exemption,Taxable Income,Regular Tax,AMTI,AMT Filers,AMT,Tax before Credits,Non-refundable Credits,Tax before Refundable Credits,Refundable Credits,Individual Income Tax Liabilities,Payroll Tax Liablities,Combined Payroll and Individual Income Tax Liabilities
0,"15,138,606","-101,873,823,642","12,828,828","87,394,772,563","17,357","69,409,647","56,298,134,736","697,085,647","69,708,565","-30,948,637,717","11,111","2,784,878,212","2,819,052,091","4,795,903","4,434,507,833","5,801,678,985","-1,367,171,152","1,696,343,620","329,172,468"
1,"15,137,593","137,814,459,749","14,544,523","112,189,769,962","150,198","1,622,397,034","84,752,107,324","10,718,973,719","1,072,551,447","1,871,235,313","2,316","59,508,739","1,094,986,062","58,257,783","4,642,667,102","21,820,573,464","-17,177,906,362","3,704,536,510","-13,473,369,852"
2,"15,138,965","229,235,041,361","14,280,564","119,621,969,590","491,482","5,985,436,598","111,134,375,367","45,631,073,638","4,635,928,414","2,942,348,319",496,"113,953,265","4,674,390,237","757,756,176","8,603,600,746","33,537,578,156","-24,933,977,410","6,158,306,751","-18,775,670,659"
3,"15,139,443","324,083,205,149","13,867,342","120,139,879,294","1,119,254","16,451,951,642","112,062,473,610","106,343,529,466","12,111,919,972","4,921,024,773","1,974","230,483,207","12,196,829,306","2,690,749,795","12,928,374,869","23,215,806,451","-10,287,431,582","8,376,485,049","-1,910,946,534"
4,"15,138,343","432,836,636,308","12,776,904","116,460,200,996","2,290,766","35,225,995,412","111,127,378,820","192,277,611,504","23,224,731,946","7,718,626,095","2,549","216,345,285","23,063,085,613","4,564,066,734","21,944,105,983","14,232,975,512","7,711,130,471","10,433,521,261","18,144,651,732"
5,"15,138,636","594,719,713,256","11,477,250","112,751,438,093","3,645,631","61,973,569,902","113,907,663,656","321,889,982,657","40,942,025,159","15,316,695,859","4,872","361,383,764","40,593,334,855","6,442,955,985","37,501,954,919","6,418,954,422","31,083,000,496","13,710,142,332","44,793,142,828"
6,"15,139,300","810,934,100,145","9,709,073","105,128,659,785","5,427,145","100,919,396,398","122,331,925,495","488,688,403,534","67,783,543,873","27,265,353,951","13,996","245,253,312","66,790,267,815","8,426,088,551","62,196,129,318","3,754,010,271","58,442,119,047","17,818,868,552","76,260,987,599"
7,"15,138,448","1,133,163,576,650","7,750,448","91,503,437,279","7,386,230","151,416,784,984","135,375,988,568","756,402,839,350","112,689,175,009","56,987,030,081","49,240","516,453,718","110,749,431,692","10,229,285,110","105,671,865,933","3,538,078,075","102,133,787,857","24,307,754,201","126,441,542,058"
8,"15,138,867","1,653,712,401,477","4,915,438","62,503,677,098","10,221,350","243,249,588,114","157,124,553,005","1,192,174,536,967","191,781,166,737","116,547,665,409","185,126","660,593,282","188,526,482,525","12,168,084,631","183,280,140,614","3,612,268,795","179,667,871,819","38,194,150,686","217,862,022,505"
9,"15,138,812","4,932,124,629,270","2,107,375","26,679,384,873","13,030,297","599,774,805,976","148,278,451,775","4,160,484,879,708","1,159,710,739,472","2,766,101,578,387","4,202,285","29,378,735,295","1,066,078,123,626","26,356,720,841","1,090,165,527,505","1,724,682,821","1,088,440,844,684","98,249,220,875","1,186,690,065,558"
sums,"151,387,013","10,146,749,939,721","104,257,746","954,373,189,533","43,779,710","1,216,689,335,707","1,152,393,052,357","7,275,308,916,189","1,614,021,490,593","2,968,722,920,470","4,473,966","34,567,588,079","1,516,585,983,823","71,698,761,509","1,531,368,874,820","117,656,606,953","1,413,712,267,867","222,649,329,837","1,636,361,597,705"

#### Create a difference table between plan X and plan Y

In [39]:
tdiff2015 = create_difference_table(calcX, calcY, groupby="weighted_deciles", income_to_present='_fica')

In [40]:
DIFF_TABLE_LABELS = ["Tax Units with Tax Cut", "Tax Units with Tax Increase",
                     "Count", "Average Tax Change", "Total Tax Difference",
                     "Percent with Tax Increase", "Percent with Tax Decrease",
                     "Share of Overall Change"]
tdiff2015.columns = DIFF_TABLE_LABELS

This difference table for payroll tax matches taxbrain/892

In [41]:
tdiff2015

,Tax Units with Tax Cut,Tax Units with Tax Increase,Count,Average Tax Change,Total Tax Difference,Percent with Tax Increase,Percent with Tax Decrease,Share of Overall Change
0,"11,682,832",0,"15,138,474",-435,"-6,586,591,409",0.00%,77.17%,0.85%
1,"13,584,995",0,"15,137,366","-1,022","-15,476,438,613",0.00%,89.74%,2.00%
2,"13,140,894",0,"15,139,393","-1,701","-25,746,739,011",0.00%,86.80%,3.32%
3,"12,249,789",0,"15,138,598","-2,273","-34,410,488,700",0.00%,80.92%,4.44%
4,"11,699,890",0,"15,139,054","-2,865","-43,373,683,045",0.00%,77.28%,5.60%
5,"12,051,055",0,"15,138,851","-3,787","-57,323,264,395",0.00%,79.60%,7.40%
6,"12,371,035",0,"15,138,689","-4,999","-75,678,448,190",0.00%,81.72%,9.77%
7,"12,906,653",0,"15,138,398","-6,862","-103,875,501,735",0.00%,85.26%,13.41%
8,"13,856,022",0,"15,138,461","-10,823","-163,844,924,078",0.00%,91.53%,21.15%
9,"14,214,919",0,"15,139,730","-16,408","-248,408,203,832",0.00%,93.89%,32.06%
sums,"127,758,083",0,"151,387,013",n/a,"-774,724,283,009",n/a,n/a,100.00%

In [42]:
tdiff2015_iit = create_difference_table(calcX, calcY, groupby="weighted_deciles", income_to_present='_iitax')

In [43]:
tdiff2015_iit.columns = DIFF_TABLE_LABELS

This difference table for ind. income tax is pretty different

In [47]:
tdiff2015_iit

,Tax Units with Tax Cut,Tax Units with Tax Increase,Count,Average Tax Change,Total Tax Difference,Percent with Tax Increase,Percent with Tax Decrease,Share of Overall Change
0,"10,725,804","196,958","15,138,474",-1,"-19,140,286",1.30%,70.85%,-0.57%
1,"4,304,030","6,045,517","15,137,366",-11,"-163,787,233",39.94%,28.43%,-4.91%
2,"2,109,732","7,699,342","15,139,393",4,"64,070,277",50.86%,13.94%,1.92%
3,"372,890","10,270,602","15,138,598",15,"228,606,769",67.84%,2.46%,6.85%
4,"124,979","10,827,621","15,139,054",16,"247,120,089",71.52%,0.83%,7.40%
5,"41,982","11,403,007","15,138,851",15,"229,587,456",75.32%,0.28%,6.88%
6,"23,145","12,051,170","15,138,689",18,"277,192,055",79.61%,0.15%,8.30%
7,909,"12,793,942","15,138,398",22,"338,353,813",84.51%,0.01%,10.14%
8,68,"12,499,663","15,138,461",40,"601,639,591",82.57%,0.00%,18.03%
9,0,"6,117,792","15,139,730",101,"1,534,134,558",40.41%,0.00%,45.96%
sums,"17,703,539","89,905,613","151,387,013",n/a,"3,337,777,088",n/a,n/a,100.00%

In [45]:
tdiff2015_combined = create_difference_table(calcX, calcY, groupby="weighted_deciles", income_to_present='_combined')
tdiff2015_combined.columns = DIFF_TABLE_LABELS

This difference table for combined iit and payroll tax matches taxbrain/893

In [46]:
tdiff2015_combined

,Tax Units with Tax Cut,Tax Units with Tax Increase,Count,Average Tax Change,Total Tax Difference,Percent with Tax Increase,Percent with Tax Decrease,Share of Overall Change
0,"11,680,019","15,581","15,138,474",-436,"-6,605,731,695",0.10%,77.15%,0.86%
1,"13,584,995","1,786","15,137,366","-1,033","-15,640,225,847",0.01%,89.74%,2.03%
2,"13,140,894","2,335","15,139,393","-1,696","-25,682,668,734",0.02%,86.80%,3.33%
3,"12,249,789","2,499","15,138,598","-2,258","-34,181,881,931",0.02%,80.92%,4.43%
4,"11,699,890",0,"15,139,054","-2,849","-43,126,562,956",0.00%,77.28%,5.59%
5,"12,049,502","4,200","15,138,851","-3,771","-57,093,676,940",0.03%,79.59%,7.40%
6,"12,371,024",11,"15,138,689","-4,981","-75,401,256,135",0.00%,81.72%,9.77%
7,"12,906,653",0,"15,138,398","-6,839","-103,537,147,922",0.00%,85.26%,13.42%
8,"13,856,022",34,"15,138,461","-10,783","-163,243,284,487",0.00%,91.53%,21.16%
9,"14,214,919",10,"15,139,730","-16,306","-246,874,069,274",0.00%,93.89%,32.00%
sums,"127,753,707","26,456","151,387,013",n/a,"-771,386,505,921",n/a,n/a,100.00%